import AethirLogo from '@/assets/logos/aethir-icon-logo.svg'
import EasierDataInitiativeLogo from '@/assets/logos/easier-data-initiative-logo.png'
import FlickrFoundationLogo from '@/assets/logos/flickr-foundation-icon-logo.svg'
import InternetArchiveLogo from '@/assets/logos/internet-archive-icon-logo.svg'
import MITOpenLearningLogo from '@/assets/logos/MIT-open-learning-icon-logo.svg'
import SetiInstituteLogo from '@/assets/logos/seti-institute-logo.svg'
import SmithsonianLogo from '@/assets/logos/smithsonian-icon-logo.png'
import SolanaLogo from '@/assets/logos/solana-icon-logo.png'
import StarlingLabLogo from '@/assets/logos/starling-lab-icon-logo.png'

import type { SimpleCardWithLogoProps } from '@/components/SimpleCardWithLogo'

const CTA_TEXT = 'Read case study'

export const caseStudies: Array<SimpleCardWithLogoProps> = [
  {
    title: 'Aethir',
    description:
      'Aethir leverages Filecoin as part of its decentralized cloud infrastructure, enabling scalable and distributed GPU compute and storage services.',
    cta: {
      href: 'https://aethir.com/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'svg',
      src: AethirLogo,
      bgColor: '#111111',
      color: '#D7FE51',
    },
  },
  {
    title: 'Easier Data Initiative',
    description:
      'The EASIER Data Initiative at the University of Maryland leverages Filecoin to make large geospatial datasets more accessible and composable.',
    cta: {
      href: 'https://www.easierdata.org/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'image',
      src: EasierDataInitiativeLogo,
      bgColor: '#ffffff',
    },
  },
  {
    title: 'Flickr Foundation',
    description:
      'Flickr Foundation is using Filecoin to help preserve thousands of historical images from cultural institutions like NASA and the U.S. National Archives.',
    cta: {
      href: 'https://www.flickr.org/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'svg',
      src: FlickrFoundationLogo,
      bgColor: '#EDEDED',
      color: '#FF0084',
    },
  },
  {
    title: 'Internet Archive',
    description:
      'Internet Archive has been leveraging Filecoin since 2021 to store various parts of their digital archive to enhance accessibility and resiliency.',
    cta: {
      href: 'https://archive.org/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'svg',
      src: InternetArchiveLogo,
      bgColor: '#222222',
      color: '#ffffff',
    },
  },
  {
    title: 'MIT Open Learning',
    description:
      "MIT Open Learning has uploaded the entire OpenCourseWare (OCW) archive to the Filecoin network, to support the institution's need for tamper-proof archiving.",
    cta: {
      href: 'https://openlearning.mit.edu/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'svg',
      src: MITOpenLearningLogo,
      bgColor: '#325B6B',
      color: '#ffffff',
    },
  },
  {
    title: 'Seti Institute',
    description:
      'The SETI Institute uses Filecoin to store and safeguard the massive datasets generated by space research.',
    cta: {
      href: 'https://www.seti.org/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'svg',
      src: SetiInstituteLogo,
      bgColor: '#000000',
      color: '#ffffff',
    },
  },
  {
    title: 'Smithsonian',
    description:
      "The Smithsonian's National Museum of American History is storing nearly 300 digitized sound records from Alexander Graham Bell on Filecoin.",
    cta: {
      href: 'https://www.si.edu/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'image',
      src: SmithsonianLogo,
      bgColor: '#101820',
    },
  },
  {
    title: 'Solana',
    description:
      "Solana leverages Filecoin's decentralized storage to archive its blockchain history, making ledger data accessible, content-addressable, and resilient.",
    cta: {
      href: 'https://solana.com/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'image',
      src: SolanaLogo,
      bgColor: '#000000',
    },
  },
  {
    title: 'Starling Labs',
    description:
      'Starling Lab is developing technology to help establish and preserve the integrity of digital media, including archiving sensitive and vulnerable records on IPFS and Filecoin.',
    cta: {
      href: 'https://www.starlinglab.org/',
      text: CTA_TEXT,
    },
    logo: {
      type: 'image',
      src: StarlingLabLogo,
      bgColor: '#FAF8F2',
    },
  },
]
