local_backend: true
backend:
  name: "git-gateway"
  branch: "main"
publish_mode: editorial_workflow
media_folder: "public/assets/images"
public_folder: "/assets/images"

header_config: &header_config
  name: "header"
  label: "Header"
  widget: "object"
  fields:
    - name: "title"
      label: "Title"
      widget: "string"
    - name: "description"
      label: "Description"
      widget: "text"

image_config: &image_config
  name: "image"
  label: "Image"
  widget: "object"
  hint: Adding an image is optional. If no image is added, a default fallback image will be used automatically. Simply leave the image field empty to use the fallback.
  fields:
    - name: "src"
      label: "URL"
      widget: "image"
      allow_multiple: false
      required: false
      hint: "Use https://squoosh.app/ to compress images before uploading. Choose the WebP format and resize the image to 2000px width."
    - name: "alt"
      label: "Alt Text"
      widget: "hidden"
      required: false
      hint: "Refer to the W3C guidelines on when to use alt text: https://www.w3.org/WAI/tutorials/images/decision-tree/. Preferably, upload the image to ChatGPT 4.0 and use the prompt: 'Check the W3C guidelines (https://www.w3.org/WAI/tutorials/images/decision-tree/) and generate appropriate alt text for this image.'"

meta_config: &meta_config
  name: "seo"
  label: "SEO Metadata"
  widget: "object"
  fields:
    - name: "title"
      label: "Meta Title"
      widget: "string"
    - name: "description"
      label: "Meta Description"
      widget: "text"
      hint: "To generate meta title and description, copy and paste the entry content into ChatGPT 4.0, then use the prompt: 'Generate a meta title and a meta description under 160 characters for the following content: [paste your content here].'"
    - name: "og"
      label: "Open Graph Metadata"
      widget: "object"
      collapsed: true
      fields:
        - name: "title"
          label: "Open Graph Title"
          widget: "string"
          required: false
        - name: "image"
          label: "Open Graph Image"
          widget: "image"
          required: false
          media_library:
            config:
              multiple: false
    - name: "twitter"
      label: "Twitter Metadata"
      widget: "object"
      collapsed: true
      fields:
        - name: "title"
          label: "Twitter Title"
          widget: "string"
          default: "summary"
          required: false
        - name: "card"
          label: "Twitter Card"
          widget: "string"
          default: "summary"
          required: false
        - name: "site"
          label: "Twitter Site"
          widget: "string"
          required: false
        - name: "creator"
          label: "Twitter Creator"
          widget: "string"
          required: false

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "src/content/pages/about.md"
        fields:
          - *header_config
          - *meta_config

      - name: "blog"
        label: "Blog"
        file: "src/content/pages/blog.md"
        fields:
          - *header_config
          - name: "featured_entry"
            label: "Featured Post"
            widget: "relation"
            collection: "blog"
            value_field: "slug"
            search_fields:
              - "slug"
              - "title"
            display_fields:
              - "title"
          - *meta_config

      - name: "ecosystem"
        label: "Ecosystem"
        file: "src/content/pages/ecosystem-explorer.md"
        fields:
          - *header_config
          - *meta_config

      - name: "employee-privacy-policy"
        label: "Employee Privacy Policy"
        file: "src/content/pages/employee-privacy-policy.md"
        fields:
          - *header_config
          - name: "featured_grant_graduates"
            label: "Featured Grant Graduates"
            widget: "relation"
            collection: "ecosystem_projects"
            value_field: "slug"
            search_fields:
              - "slug"
              - "title"
            display_fields:
              - "title"
            multiple: true
            min: 6
            max: 6
          - *meta_config

      - name: "events"
        label: "Events"
        file: "src/content/pages/events.md"
        fields:
          - *header_config
          - name: "featured_entry"
            label: "Featured Event"
            widget: "relation"
            collection: "events"
            value_field: "slug"
            search_fields:
              - "slug"
              - "title"
            display_fields:
              - "title"
          - *meta_config

      - name: "filecoin-plus"
        label: "Filecoin Plus"
        file: "src/content/pages/filecoin-plus.md"
        fields:
          - *header_config
          - *meta_config

      - name: "governance"
        label: "Governance"
        file: "src/content/pages/governance.md"
        fields:
          - *header_config
          - *meta_config

      - name: "grants"
        label: "Grants"
        file: "src/content/pages/grants.md"
        fields:
          - *header_config
          - *meta_config

      - name: "home"
        label: "Home"
        file: "src/content/pages/home.md"
        fields:
          - *header_config
          - name: "featured_ecosystem_projects"
            label: "Featured Ecosystem Projects"
            widget: "relation"
            collection: "ecosystem_projects"
            value_field: "slug"
            search_fields:
              - "slug"
              - "title"
            display_fields:
              - "title"
            multiple: true
            min: 6
            max: 6
          - *meta_config

      - name: "privacy-policy"
        label: "Privacy Policy"
        file: "src/content/pages/privacy-policy.md"
        fields:
          - *header_config
          - *meta_config

      - name: "terms"
        label: "Terms"
        file: "src/content/pages/terms-of-use.md"
        fields:
          - *header_config
          - *meta_config

  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/blog/"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
      - name: "category"
        label: "Category"
        widget: "select"
        options:
          - label: "Ecosystem"
            value: "ecosystem"
          - label: "Events"
            value: "events"
          - label: "Interviews"
            value: "interviews"
          - label: "News"
            value: "news"
          - label: "Reports"
            value: "reports"
          - label: "Use Cases"
            value: "use-cases"
      - name: "description"
        label: "Description"
        widget: "text"
      - *image_config
      - name: "body"
        label: "Content"
        widget: "markdown"
        editor_components:
          - "code-block"
          - "image"
          - "video"
          - "audio"
        required: false
      - name: "recommended-posts"
        label: "Recommended Posts"
        widget: "hidden"
        required: false
        collection: "blog"
        value_field: "src/content/blog/{{slug}}.md"
        search_fields:
          - "slug"
          - "title"
        display_fields:
          - "title"
        multiple: true
      - *meta_config

  - name: "ecosystem_projects_categories"
    label: "Ecosystem Projects Categories"
    label_singular: Ecosystem Projects Category
    folder: "src/content/ecosystem-explorer/categories/"
    create: true
    identifier_field: name
    extension: "yml"
    slug: "{{slug}}"
    fields:
      - name: "name"
        label: "Category Name"
        widget: "string"
      - name: "subcategories"
        label: "Subcategories"
        widget: "relation"
        collection: "ecosystem_projects_subcategories"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true

  - name: "ecosystem_projects_subcategories"
    label: "Ecosystem Projects Subcategories"
    label_singular: Ecosystem Projects Subcategory
    folder: "src/content/ecosystem-explorer/subcategories/"
    create: true
    identifier_field: name
    extension: "yml"
    slug: "{{slug}}"
    fields:
      - label: "Subcategory Name"
        name: "name"
        widget: "string"
      - label: "Parent Category"
        name: "parent_category"
        widget: "relation"
        collection: "ecosystem_projects_categories"
        search_fields:
          - name
        value_field: "slug"
        display_fields:
          - name

  - name: ecosystem_projects
    label: Ecosystem Projects
    label_singular: Ecosystem Project
    folder: "src/content/ecosystem-explorer/projects/"
    create: true
    extension: md
    slug: "{{slug}}"
    fields:
      - name: title
        label: Company Name
        widget: string
      - name: created-on
        label: Created On
        widget: datetime
      - name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - name: published-on
        label: Published On
        widget: datetime
        required: false
      - *image_config
      - name: category
        label: Category
        widget: relation
        collection: "ecosystem_projects_categories"
        value_field: "slug"
        search_fields:
          - name
        display_fields:
          - name
      - name: subcategories
        label: Subcategories
        widget: relation
        collection: "ecosystem_projects_subcategories"
        value_field: "slug"
        search_fields:
          - name
        display_fields:
          - name
        multiple: true
        filter:
          field: "parent_category"
          value: "{{fields.category}}"
      - name: tags
        label: Tags
        widget: hidden
        required: false
        multiple: true
        options:
          - label: "AI Productivity & Utilities"
            value: ai-productivity-and-utilities
          - label: "Arts & Collectibles"
            value: arts-collectibles
          - label: "Bridges & Oracles"
            value: bridges-oracles
          - label: "Climate"
            value: climate
          - label: "Communication & Social"
            value: communication-social
          - label: "DApp"
            value: dapp
          - label: "Data Curation & Monetization"
            value: data-curation-monetization
          - label: "Data Preparation"
            value: data-prep
          - label: "Data Retrieval"
            value: data-retrieval
          - label: "Data Storage & Management"
            value: data-storage-management
          - label: "Decentralized Personal Information Networks"
            value: depin
          - label: "Decentralized Science"
            value: desci
          - label: "Developer Tools"
            value: developer-tools
          - label: "DWeb"
            value: dweb
          - label: "Enterprise"
            value: enterprise
          - label: "Gaming"
            value: gaming
          - label: "GLAM (Galleries, Libraries, Archives, Museums)"
            value: glam
          - label: "Governance, DAOs, & Public Goods"
            value: governance-daos-public-goods
          - label: "GPUs"
            value: gpus
          - label: "Health"
            value: health
          - label: "Infrastructure"
            value: infrastructure
          - label: "Leasing & Staking"
            value: leasing-and-staking
          - label: "Metaverse"
            value: metaverse
          - label: "Network Tools"
            value: network-tools
          - label: "NFTs"
            value: nfts
          - label: "Photo & Video"
            value: photo-video
          - label: "Privacy & Security"
            value: privacy-security
          - label: "Public Data"
            value: public-data
          - label: "Publishing & News"
            value: publishing-news
          - label: "RSS"
            value: rss
          - label: "S3 APIs"
            value: s3-apis
          - label: "Sealing"
            value: sealing
          - label: "Social Impact"
            value: social-impact
          - label: "Space"
            value: space
          - label: "Storage Infrastructure"
            value: storage-infrastructure
          - label: "Storage Provider"
            value: storage-provider
          - label: "Storage Services"
            value: storage-services
          - label: "Storage Software"
            value: storage-software
          - label: "Universities"
            value: universities
          - label: "Wallets, Identity & Authentication"
            value: wallets-identity-authentication
            multiple: true
      - name: description
        label: Short Description
        widget: string
        hint: "A short description of the project. Maximum 160 characters."
        pattern:
          - "^.{0,160}$"
          - "Description must be 160 characters or less."
      - name: website
        label: Website
        widget: string
      - name: tech
        label: Technologies Used
        widget: select
        multiple: true
        options:
          - filecoin
          - ipfs
      - name: repo
        label: GitHub Repo
        widget: string
        required: false
      - name: featured-content
        label: Featured Content
        widget: string
        required: false
      - name: twitter
        label: Twitter Handle
        widget: string
        required: false
      - name: video-url
        label: YouTube Video URL
        widget: string
        required: false
      - name: year-joined
        label: Using Filecoin Since
        widget: datetime
        required: false
      - name: body
        label: Long Description
        widget: markdown
        required: false
      - name: news-update
        label: What's New?
        widget: text
        required: false
      - *meta_config

  - name: "events"
    label: "Events"
    folder: "src/content/events/"
    label_singular: "Event"
    create: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
      - name: "category"
        label: "Category"
        widget: "select"
        options:
          - label: "Co-Hosted"
            value: "co-hosted"
          - label: "Community"
            value: "community"
          - label: "Hosted"
            value: "hosted"
          - label: "Supported & Sponsored"
            value: "supported-sponsored"
      - name: "description"
        label: "Description"
        widget: "string"
        required: false
      - name: "location"
        label: "Location"
        widget: "string"
      - name: "external-link"
        label: "External Link URL"
        widget: "string"
        required: false
        hint: "External link to the event page"
      - name: "start-date"
        label: "Start Date"
        widget: "datetime"
        hint: "First day of event"
      - name: "end-date"
        label: "End Date"
        widget: "datetime"
        required: false
        hint: "Last day of event"
      - *image_config
      - *meta_config
