export const CATEGORY_KEY = 'category'
export const LOCATION_KEY = 'location'
export const PAGE_KEY = 'page'
export const SEARCH_KEY = 'search'
export const SORT_KEY = 'sort'
export const RESOURCE = 'resource'
export const PARTNERSHIP_KEY = 'partnership'
