name: Lint Code Base

on:
  push:
    branches:
      - main
      - cms/*
      - ecosystem-submission/*
  pull_request:
    branches:
      - main
      - cms/*
      - ecosystem-submission/*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm install

      - name: Generate CMS configuration schema
        run: npm run prebuild

      - name: Run linter
        run: npm run lint
