name: Lint Code Base

on:
  push:
    branches:
      - main
      - cms/*
      - ecosystem-submission/*
  pull_request:
    branches:
      - main
      - cms/*
      - ecosystem-submission/*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm install

      - name: Generate CMS configuration schema
        run: npm run prebuild

      - name: Run linter
        run: npm run lint

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: "C07UH9HAURX"
          slack-message: |
            ${{ github.actor }} opened a pull request: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
