name: Slack Notification for PR Review Ready

on:
  pull_request:
    types: [ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Reviewers List for Slack
        id: format_reviewers
        run: |
          REVIEWERS=$(echo "${{ toJson(github.event.pull_request.requested_reviewers) }}" | jq -r '.[].login' | paste -sd ", " -)
          if [ -z "$REVIEWERS" ]; then
            REVIEWERS="No reviewers assigned"
          fi
          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.27.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C07UH9HAURX
          slack-message: |
            ${{ github.actor }} has marked a pull request as ready for review: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
            Reviewers: ${{ env.reviewers }}
