name: Notify Slack on Open PR

on:
  pull_request:
    types: [opened]
    branches:
      - main
      - cms/*
      - ecosystem-submission/*

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify Slack
        uses: pullreminders/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: |
            {
              "channel": "C07UH9HAURX",
              "text": "A new pull request has been opened on the ${{ github.ref_name }} branch!"
            }
