name: Turborepo Cache Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ff-site, ffdweb-site, uxit]

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo/cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx turbo run build --filter="./apps/${{ matrix.app }}"
        env:
          AIRTABLE_READ_ONLY_TOKEN: ${{ secrets.AIRTABLE_READ_ONLY_TOKEN }}
          PERCY_TOKEN: ${{ (matrix.app == 'ff-site' && secrets.PERCY_TOKEN_FF_SITE) || secrets.PERCY_TOKEN_FFDWEB_SITE }}
          ENCRYPTION_SECRET_KEY: "a-random-key-so-that-ci-builds-dont-fail"
