name: Apps PR Review Notification

on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
      pr_title:
        description: "Pull Request Title"
        required: true
      pr_url:
        description: "Pull Request URL"
        required: true
      reviewers:
        description: "Reviewers (comma-separated)"
        required: false
        default: "No reviewers assigned"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Event Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event path: $GITHUB_EVENT_PATH"
          echo "Changed files:"
          cat $GITHUB_EVENT_PATH | jq '.pull_request.changed_files'
          echo "Repository: ${{ github.repository }}"
          echo "Reference: ${{ github.ref }}"

      - name: Prepare Reviewers List and App Info
        id: format_info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REVIEWERS="${{ github.event.inputs.reviewers }}"
            APP_PATH="apps/site"
            PR_URL="${{ github.event.inputs.pr_url }}"
            PR_TITLE="${{ github.event.inputs.pr_title }}"
          else
            REVIEWERS=$(echo "${{ toJson(github.event.pull_request.requested_reviewers) }}" | jq -r '.[].login' | paste -sd ", " -)
            APP_PATH=$(echo "${{ github.event.pull_request.changed_files }}" | grep -o 'apps/[^/]*' | head -1)
            if [ -z "$REVIEWERS" ]; then
              REVIEWERS="No reviewers assigned"
            fi
            PR_URL="${{ github.event.pull_request.html_url }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
          fi
          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          payload: |
            {
              "channel": "C07UH9HAURX",
              "text": "${{ github.actor }} has marked a pull request as ready for review in ${{ env.APP_PATH }}: <${{ env.PR_URL }}|${{ env.PR_TITLE }}>\nReviewers: ${{ env.REVIEWERS }}"
            }
