name: Apps PR Review Notification

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
      pr_title:
        description: "Pull Request Title"
        required: true
      pr_url:
        description: "Pull Request URL"
        required: true
      reviewers:
        description: "Reviewers (comma-separated)"
        required: false
        default: "No reviewers assigned"

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Reviewers List and App Info
        id: prepare_info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "reviewers=${{ github.event.inputs.reviewers }}" >> $GITHUB_OUTPUT
            echo "app_path=apps/site" >> $GITHUB_OUTPUT
            echo "pr_url=${{ github.event.inputs.pr_url }}" >> $GITHUB_OUTPUT
            echo "pr_title=${{ github.event.inputs.pr_title }}" >> $GITHUB_OUTPUT
          else
            REVIEWERS=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq -r '.[].login' | paste -sd ", " -)
            if [ -z "$REVIEWERS" ]; then
              REVIEWERS="No reviewers assigned"
            fi
            echo "reviewers=$REVIEWERS" >> $GITHUB_OUTPUT
            echo "app_path=apps/site" >> $GITHUB_OUTPUT
            echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
            echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "channel": "C07UH9HAURX",
              "text": "${{ github.actor }} has marked a pull request as ready for review in ${{ steps.prepare_info.outputs.app_path }}: <${{ steps.prepare_info.outputs.pr_url }}|${{ steps.prepare_info.outputs.pr_title }}>\nReviewers: ${{ steps.prepare_info.outputs.reviewers }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
