name: Site Turborepo Cache Build

on:
  push:
    paths:
      - "apps/**"
    branches: [main]
  pull_request:
    paths:
      - "apps/**"
    branches: [main]

jobs:
  cache-build:
    runs-on: ubuntu-latest

    env:
      AIRTABLE_READ_ONLY_TOKEN: ${{ secrets.AIRTABLE_READ_ONLY_TOKEN }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      ENCRYPTION_SECRET_KEY: "a-random-key-so-that-ci-builds-dont-fail"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: "filecoin-foundations-projects"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
