name: Site Cypress and Percy Tests

on:
  push:
    paths:
      - "apps/site/**"
    branches: [main]
  pull_request:
    paths:
      - "apps/site/**"
    branches: [main]

jobs:
  cypress-run:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    env:
      AIRTABLE_READ_ONLY_TOKEN: ${{ secrets.AIRTABLE_READ_ONLY_TOKEN }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      ENCRYPTION_SECRET_KEY: "a-random-key-so-that-ci-builds-dont-fail"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        working-directory: ./apps/site
        run: npm run build

      - name: Start Server
        working-directory: ./apps/site
        run: |
          npm start &
          echo "Waiting for server to start..."
          npx wait-on http://localhost:3000

      - name: Determine Test Type
        id: test-type
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.head_ref }}"
            COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          fi

          if [[ "$BRANCH_NAME" == cms/* ]] || [[ "$COMMIT_MESSAGE" == *"[skip percy]"* ]]; then
            echo "skip_percy=true" >> $GITHUB_OUTPUT
          else
            echo "skip_percy=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Cypress Tests without Percy
        if: steps.test-type.outputs.skip_percy == 'true'
        working-directory: ./apps/site
        run: npm run test:cypress

      - name: Run Cypress Tests with Percy
        if: steps.test-type.outputs.skip_percy == 'false'
        working-directory: ./apps/site
        run: npm run test:cypress:percy
