name: Site Turborepo Cache Build

on:
  push:
    paths:
      - "apps/**"
    branches: [main]
  pull_request:
    paths:
      - "apps/**"
    branches: [main]

jobs:
  cache-build:
    runs-on: ubuntu-latest

    env:
      AIRTABLE_READ_ONLY_TOKEN: ${{ secrets.AIRTABLE_READ_ONLY_TOKEN }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      ENCRYPTION_SECRET_KEY: "a-random-key-so-that-ci-builds-dont-fail"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: "filecoin-foundations-projects"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm ci

      - name: Setup Turborepo remote caching
        run: npx turbo build --cache-dir=".turbo"
